// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>

namespace oaktree_gen {

class Chef;
class Handler;
class Service;
class System;

class Api {
public:
    virtual ~Api() {}

    virtual std::shared_ptr<Chef> get_chef() = 0;

    static std::shared_ptr<Api> get_instance(const std::shared_ptr<System> & sys, const std::shared_ptr<Handler> & handler, const std::shared_ptr<Service> & service);
};

}  // namespace oaktree_gen
