// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>
#include <string>

namespace oaktree_gen {

class Dish;
class Recipe;
class System;
enum class Menu;

class Chef {
public:
    virtual ~Chef() {}

    virtual std::string get_version() = 0;

    virtual std::shared_ptr<Dish> grab(Menu menu) = 0;

    virtual void add_recipe(const std::shared_ptr<Recipe> & recipe) = 0;

    static std::shared_ptr<System> get_system();
};

}  // namespace oaktree_gen
