// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>
#include <string>
#include <unordered_map>

namespace oaktree_gen {

class ServiceBinder;
enum class Package;

class Dish {
public:
    virtual ~Dish() {}

    virtual void serve(Package package_list, const std::unordered_map<std::string, std::string> & params, const std::shared_ptr<ServiceBinder> & binder) = 0;
};

}  // namespace oaktree_gen
