// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <functional>

namespace oaktree_gen {

enum class LoadType : int {
    LAZY,
    STRICT,
    STATIC,
};

}  // namespace oaktree_gen

namespace std {

template <>
struct hash<::oaktree_gen::LoadType> {
    size_t operator()(::oaktree_gen::LoadType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
