// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <functional>

namespace oaktree_gen {

enum class Menu : int {
    CONFIG_MODULE,
    CATALOG_MODULE,
    CHECKOUT_MODULE,
};

}  // namespace oaktree_gen

namespace std {

template <>
struct hash<::oaktree_gen::Menu> {
    size_t operator()(::oaktree_gen::Menu type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
