// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <functional>

namespace oaktree_gen {

enum class Package : int {
    USER_RECOVER,
    USER_ADDRESS,
    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,
    STORE_LIST,
    STORE_VIEW,
    SAVE_STORE,
    ALLOWED_LOCATION,
    START_APPLICATION,
    START_SESSION,
    PRODUCT_LIST,
    PRODUCT_UPLOAD,
    PRODUCT_USER_PRODUCTS,
    PRODUCT_DETAIL,
    PRODUCT_UPDATE_CART,
    PRODUCT_GET_CART,
    PRODUCT_ADD_TO_CART,
    BANNERS,
    RECENT_PRODUCTS,
    CATEGORY_LIST,
};

}  // namespace oaktree_gen

namespace std {

template <>
struct hash<::oaktree_gen::Package> {
    size_t operator()(::oaktree_gen::Package type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
