// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>

namespace oaktree_gen {

class Dish;
enum class Menu;

class Recipe {
public:
    virtual ~Recipe() {}

    virtual std::shared_ptr<Dish> get_dish() = 0;

    virtual Menu get_menu() = 0;
};

}  // namespace oaktree_gen
