// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

namespace oaktree_gen {

class Runnable {
public:
    virtual ~Runnable() {}

    virtual void run() = 0;
};

}  // namespace oaktree_gen
