// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#pragma once

#include <memory>

namespace oaktree_gen {

class Chef;

class Sandwich {
public:
    virtual ~Sandwich() {}

    virtual void get_recipe(const std::shared_ptr<Chef> & chef) = 0;

    static std::shared_ptr<Sandwich> get_instance();
};

}  // namespace oaktree_gen
