// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>
#include <string>

namespace oaktree_gen {

class SimpleCursor;
enum class LoadType;

class ServiceBinder {
public:
    virtual ~ServiceBinder() {}

    virtual LoadType load_type() = 0;

    virtual void on_error(const std::string & message) = 0;

    virtual void on_load(const std::string & message, bool cache, const std::shared_ptr<SimpleCursor> & cursor) = 0;
};

}  // namespace oaktree_gen
