// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>
#include <string>

namespace oaktree_gen {

class Handler;
class Runnable;

class Service {
public:
    virtual ~Service() {}

    virtual std::shared_ptr<Handler> pool_handler() = 0;

    virtual void on_create() = 0;

    virtual void on_start(const std::string & name, const std::shared_ptr<Runnable> & runnable) = 0;
};

}  // namespace oaktree_gen
