// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace oaktree_gen {

class SimpleCursor {
public:
    virtual ~SimpleCursor() {}

    virtual void close() = 0;

    virtual void reset() = 0;

    virtual int32_t get_count() = 0;

    virtual int32_t get_position() = 0;

    virtual std::vector<std::string> get_column_names() = 0;

    virtual bool is_last() = 0;

    virtual bool is_first() = 0;

    virtual bool is_closed() = 0;

    virtual std::string get_string(const std::string & column_name) = 0;

    virtual bool move_to_next() = 0;

    virtual bool move_to_last() = 0;

    virtual bool move_to_first() = 0;

    virtual bool move_to_previous() = 0;

    virtual bool move_to_position(int32_t position) = 0;

    virtual std::string to_json() = 0;
};

}  // namespace oaktree_gen
