// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include <memory>
#include <string>

namespace oaktree_gen {

class SimpleCursor;

class System {
public:
    virtual ~System() {}

    virtual std::string get_path() = 0;

    virtual std::shared_ptr<SimpleCursor> query(const std::string & database, const std::string & query) = 0;
};

}  // namespace oaktree_gen
