# This file is generated by gyp; do not edit.


LOCAL_PATH := $(call my-dir)
GYP_CONFIGURATION ?= Debug
GYP_VAR_PREFIX ?=
GYP_HOST_VAR_PREFIX ?=
GYP_HOST_MULTILIB ?=

include $(LOCAL_PATH)/application/libapplication_jni.target.mk
include $(LOCAL_PATH)/core/deps/curlcpp_jni.target.mk
include $(LOCAL_PATH)/core/deps/restful_mapper_jni.target.mk
include $(LOCAL_PATH)/core/deps/sqlite3.target.mk
include $(LOCAL_PATH)/core/deps/yajl.target.mk
include $(LOCAL_PATH)/core/oaktree/liboaktree_jni.target.mk
include $(LOCAL_PATH)/core/support-lib/djinni_jni.target.mk

# "gyp_all_modules" is a concatenation of the "gyp_all_modules" targets from
# all the included sub-makefiles. This is just here to clarify.
gyp_all_modules:
