// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "service.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol OAKLIBService;

namespace djinni_generated {

class Service
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Service>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Service>;
    using ObjcType = id<OAKLIBService>;

    using Boxed = Service;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

