// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "handler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol OAKLIBHandler;

namespace djinni_generated {

class Handler
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Handler>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Handler>;
    using ObjcType = id<OAKLIBHandler>;

    using Boxed = Handler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

