// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBPackage.h"
#import <Foundation/Foundation.h>
@protocol OAKLIBServiceBinder;


@interface OAKLIBDish : NSObject

- (void)serve:(OAKLIBPackage)packageList
       params:(nonnull NSDictionary<NSString *, NSString *> *)params
       binder:(nullable id<OAKLIBServiceBinder>)binder;

@end
