// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>
@class OAKLIBRunnable;
@protocol OAKLIBHandler;


@protocol OAKLIBService

- (nullable id<OAKLIBHandler>)poolHandler;

- (void)onCreate;

- (void)onStart:(nonnull NSString *)name
       runnable:(nullable OAKLIBRunnable *)runnable;

@end
