// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>
@class OAKLIBRunnable;


@protocol OAKLIBHandler

- (void)post:(nullable OAKLIBRunnable *)runnable;

@end
