// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBDish+Private.h"
#import "OAKLIBDish.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "OAKLIBPackage+Private.h"
#import "OAKLIBServiceBinder+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface OAKLIBDish ()

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Dish>&)cppRef;

@end

@implementation OAKLIBDish {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::oaktree_gen::Dish>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Dish>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)serve:(OAKLIBPackage)packageList
       params:(nonnull NSDictionary<NSString *, NSString *> *)params
       binder:(nullable id<OAKLIBServiceBinder>)binder {
    try {
        _cppRefHandle.get()->serve(::djinni::Enum<::oaktree_gen::Package, OAKLIBPackage>::toCpp(packageList),
                                   ::djinni::Map<::djinni::String, ::djinni::String>::toCpp(params),
                                   ::djinni_generated::ServiceBinder::toCpp(binder));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Dish::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Dish::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<OAKLIBDish>(cpp);
}

}  // namespace djinni_generated

@end
