// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBApi+Private.h"
#import "OAKLIBApi.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "OAKLIBChef+Private.h"
#import "OAKLIBHandler+Private.h"
#import "OAKLIBService+Private.h"
#import "OAKLIBSystem+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface OAKLIBApi ()

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Api>&)cppRef;

@end

@implementation OAKLIBApi {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::oaktree_gen::Api>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Api>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nullable OAKLIBChef *)getChef {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_chef();
        return ::djinni_generated::Chef::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable OAKLIBApi *)getInstance:(nullable id<OAKLIBSystem>)sys
                            handler:(nullable id<OAKLIBHandler>)handler
                            service:(nullable id<OAKLIBService>)service {
    try {
        auto objcpp_result_ = ::oaktree_gen::Api::get_instance(::djinni_generated::System::toCpp(sys),
                                                               ::djinni_generated::Handler::toCpp(handler),
                                                               ::djinni_generated::Service::toCpp(service));
        return ::djinni_generated::Api::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Api::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Api::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<OAKLIBApi>(cpp);
}

}  // namespace djinni_generated

@end
