// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "recipe.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OAKLIBRecipe;

namespace djinni_generated {

class Recipe
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Recipe>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Recipe>;
    using ObjcType = OAKLIBRecipe*;

    using Boxed = Recipe;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

