// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#include "sandwich.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OAKLIBSandwich;

namespace djinni_generated {

class Sandwich
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Sandwich>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Sandwich>;
    using ObjcType = OAKLIBSandwich*;

    using Boxed = Sandwich;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

