// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#import "OAKLIBSandwich+Private.h"
#import "OAKLIBSandwich.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "OAKLIBChef+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface OAKLIBSandwich ()

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Sandwich>&)cppRef;

@end

@implementation OAKLIBSandwich {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::oaktree_gen::Sandwich>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::oaktree_gen::Sandwich>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)getRecipe:(nullable OAKLIBChef *)chef {
    try {
        _cppRefHandle.get()->get_recipe(::djinni_generated::Chef::toCpp(chef));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable OAKLIBSandwich *)getInstance {
    try {
        auto objcpp_result_ = ::oaktree_gen::Sandwich::get_instance();
        return ::djinni_generated::Sandwich::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Sandwich::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Sandwich::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<OAKLIBSandwich>(cpp);
}

}  // namespace djinni_generated

@end
