// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>
@protocol OAKLIBSimpleCursor;


@protocol OAKLIBSystem

- (nonnull NSString *)getPath;

- (nullable id<OAKLIBSimpleCursor>)query:(nonnull NSString *)database
                                   query:(nonnull NSString *)query;

@end
