// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "chef.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OAKLIBChef;

namespace djinni_generated {

class Chef
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Chef>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Chef>;
    using ObjcType = OAKLIBChef*;

    using Boxed = Chef;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

