// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBHandler+Private.h"
#import "OAKLIBHandler.h"
#import "DJIObjcWrapperCache+Private.h"
#import "OAKLIBRunnable+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class Handler::ObjcProxy final
: public ::oaktree_gen::Handler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::Handler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void post(const std::shared_ptr<::oaktree_gen::Runnable> & c_runnable) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() post:(::djinni_generated::Runnable::fromCpp(c_runnable))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto Handler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto Handler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
