// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBMenu.h"
#import <Foundation/Foundation.h>
@class OAKLIBDish;


@interface OAKLIBRecipe : NSObject

- (nullable OAKLIBDish *)getDish;

- (OAKLIBMenu)getMenu;

@end
