// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "simple_cursor.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol OAKLIBSimpleCursor;

namespace djinni_generated {

class SimpleCursor
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::SimpleCursor>;
    using CppOptType = std::shared_ptr<::oaktree_gen::SimpleCursor>;
    using ObjcType = id<OAKLIBSimpleCursor>;

    using Boxed = SimpleCursor;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

