// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBServiceBinder+Private.h"
#import "OAKLIBServiceBinder.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "OAKLIBLoadType+Private.h"
#import "OAKLIBSimpleCursor+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ServiceBinder::ObjcProxy final
: public ::oaktree_gen::ServiceBinder
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::ServiceBinder;
public:
    using ObjcProxyBase::ObjcProxyBase;
    ::oaktree_gen::LoadType load_type() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() loadType];
            return ::djinni::Enum<::oaktree_gen::LoadType, OAKLIBLoadType>::toCpp(objcpp_result_);
        }
    }
    void on_error(const std::string & c_message) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onError:(::djinni::String::fromCpp(c_message))];
        }
    }
    void on_load(const std::string & c_message, bool c_cache, const std::shared_ptr<::oaktree_gen::SimpleCursor> & c_cursor) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoad:(::djinni::String::fromCpp(c_message))
                                                       cache:(::djinni::Bool::fromCpp(c_cache))
                                                      cursor:(::djinni_generated::SimpleCursor::fromCpp(c_cursor))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ServiceBinder::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ServiceBinder::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
