// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBSystem+Private.h"
#import "OAKLIBSystem.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "OAKLIBSimpleCursor+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class System::ObjcProxy final
: public ::oaktree_gen::System
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::System;
public:
    using ObjcProxyBase::ObjcProxyBase;
    std::string get_path() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() getPath];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
    std::shared_ptr<::oaktree_gen::SimpleCursor> query(const std::string & c_database, const std::string & c_query) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() query:(::djinni::String::fromCpp(c_database))
                                                                            query:(::djinni::String::fromCpp(c_query))];
            return ::djinni_generated::SimpleCursor::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto System::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto System::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
