// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>


@protocol OAKLIBSimpleCursor

- (void)close;

- (void)reset;

- (int32_t)getCount;

- (int32_t)getPosition;

- (nonnull NSArray<NSString *> *)getColumnNames;

- (BOOL)isLast;

- (BOOL)isFirst;

- (BOOL)isClosed;

- (nonnull NSString *)getString:(nonnull NSString *)columnName;

- (BOOL)moveToNext;

- (BOOL)moveToLast;

- (BOOL)moveToFirst;

- (BOOL)moveToPrevious;

- (BOOL)moveToPosition:(int32_t)position;

- (nonnull NSString *)toJson;

@end
