// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "dish.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OAKLIBDish;

namespace djinni_generated {

class Dish
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Dish>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Dish>;
    using ObjcType = OAKLIBDish*;

    using Boxed = Dish;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

