// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>
@class OAKLIBApi;
@class OAKLIBChef;
@protocol OAKLIBHandler;
@protocol OAKLIBService;
@protocol OAKLIBSystem;


@interface OAKLIBApi : NSObject

- (nullable OAKLIBChef *)getChef;

+ (nullable OAKLIBApi *)getInstance:(nullable id<OAKLIBSystem>)sys
                            handler:(nullable id<OAKLIBHandler>)handler
                            service:(nullable id<OAKLIBService>)service;

@end
