// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBMenu.h"
#import <Foundation/Foundation.h>
@class OAKLIBDish;
@class OAKLIBRecipe;
@protocol OAKLIBSystem;


@interface OAKLIBChef : NSObject

- (nonnull NSString *)getVersion;

- (nullable OAKLIBDish *)grab:(OAKLIBMenu)menu;

- (void)addRecipe:(nullable OAKLIBRecipe *)recipe;

+ (nullable id<OAKLIBSystem>)getSystem;

@end
