// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import "OAKLIBLoadType.h"
#import <Foundation/Foundation.h>
@protocol OAKLIBSimpleCursor;


@protocol OAKLIBServiceBinder

- (OAKLIBLoadType)loadType;

- (void)onError:(nonnull NSString *)message;

- (void)onLoad:(nonnull NSString *)message
         cache:(BOOL)cache
        cursor:(nullable id<OAKLIBSimpleCursor>)cursor;

@end
