// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#import <Foundation/Foundation.h>
@class OAKLIBTest;


@interface OAKLIBTest : NSObject

- (nonnull NSString *)getName;

+ (nullable OAKLIBTest *)create;

@end
