// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#import <Foundation/Foundation.h>
@class OAKLIBChef;
@class OAKLIBSandwich;


@interface OAKLIBSandwich : NSObject

- (void)getRecipe:(nullable OAKLIBChef *)chef;

+ (nullable OAKLIBSandwich *)getInstance;

@end
