// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "runnable.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OAKLIBRunnable;

namespace djinni_generated {

class Runnable
{
public:
    using CppType = std::shared_ptr<::oaktree_gen::Runnable>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Runnable>;
    using ObjcType = OAKLIBRunnable*;

    using Boxed = Runnable;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

