// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>
@class SBTest;


@interface SBTest : NSObject

- (nonnull NSString *)getName;

+ (nullable SBTest *)create;

@end
