// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "chef.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeChef final : ::djinni::JniInterface<::oaktree_gen::Chef, NativeChef> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Chef>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Chef>;
    using JniType = jobject;

    using Boxed = NativeChef;

    ~NativeChef();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeChef>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeChef>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeChef();
    friend ::djinni::JniClass<NativeChef>;
    friend ::djinni::JniInterface<::oaktree_gen::Chef, NativeChef>;

};

}  // namespace djinni_generated
