// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "dish.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDish final : ::djinni::JniInterface<::oaktree_gen::Dish, NativeDish> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Dish>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Dish>;
    using JniType = jobject;

    using Boxed = NativeDish;

    ~NativeDish();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDish>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDish>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDish();
    friend ::djinni::JniClass<NativeDish>;
    friend ::djinni::JniInterface<::oaktree_gen::Dish, NativeDish>;

};

}  // namespace djinni_generated
