// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "djinni_support.hpp"
#include "handler.hpp"

namespace djinni_generated {

class NativeHandler final : ::djinni::JniInterface<::oaktree_gen::Handler, NativeHandler> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Handler>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Handler>;
    using JniType = jobject;

    using Boxed = NativeHandler;

    ~NativeHandler();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHandler>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHandler>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHandler();
    friend ::djinni::JniClass<NativeHandler>;
    friend ::djinni::JniInterface<::oaktree_gen::Handler, NativeHandler>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::oaktree_gen::Handler
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void post(const std::shared_ptr<::oaktree_gen::Runnable> & runnable) override;

    private:
        friend ::djinni::JniInterface<::oaktree_gen::Handler, ::djinni_generated::NativeHandler>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/siliconbear/oakstore/Handler") };
    const jmethodID method_post { ::djinni::jniGetMethodID(clazz.get(), "post", "(Lcom/siliconbear/oakstore/Runnable;)V") };
};

}  // namespace djinni_generated
