// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "NativeApi.hpp"  // my header
#include "NativeChef.hpp"
#include "NativeHandler.hpp"
#include "NativeService.hpp"
#include "NativeSystem.hpp"

namespace djinni_generated {

NativeApi::NativeApi() : ::djinni::JniInterface<::oaktree_gen::Api, NativeApi>("com/siliconbear/oakstore/Api$CppProxy") {}

NativeApi::~NativeApi() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_oakstore_Api_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::oaktree_gen::Api>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_oakstore_Api_00024CppProxy_native_1getChef(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::oaktree_gen::Api>(nativeRef);
        auto r = ref->get_chef();
        return ::djinni::release(::djinni_generated::NativeChef::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_oakstore_Api_getInstance(JNIEnv* jniEnv, jobject /*this*/, jobject j_sys, jobject j_handler, jobject j_service)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::oaktree_gen::Api::get_instance(::djinni_generated::NativeSystem::toCpp(jniEnv, j_sys),
                                                  ::djinni_generated::NativeHandler::toCpp(jniEnv, j_handler),
                                                  ::djinni_generated::NativeService::toCpp(jniEnv, j_service));
        return ::djinni::release(::djinni_generated::NativeApi::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
