// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#pragma once

#include "djinni_support.hpp"
#include "product.hpp"

namespace djinni_generated {

class NativeProduct final : ::djinni::JniInterface<::oaktree_gen::Product, NativeProduct> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Product>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Product>;
    using JniType = jobject;

    using Boxed = NativeProduct;

    ~NativeProduct();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeProduct>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeProduct>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeProduct();
    friend ::djinni::JniClass<NativeProduct>;
    friend ::djinni::JniInterface<::oaktree_gen::Product, NativeProduct>;

};

}  // namespace djinni_generated
