// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "djinni_support.hpp"
#include "load_type.hpp"

namespace djinni_generated {

class NativeLoadType final : ::djinni::JniEnum {
public:
    using CppType = ::oaktree_gen::LoadType;
    using JniType = jobject;

    using Boxed = NativeLoadType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeLoadType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeLoadType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeLoadType() : JniEnum("com/siliconbear/oakstore/LoadType") {}
    friend ::djinni::JniClass<NativeLoadType>;
};

}  // namespace djinni_generated
