// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "djinni_support.hpp"
#include "menu.hpp"

namespace djinni_generated {

class NativeMenu final : ::djinni::JniEnum {
public:
    using CppType = ::oaktree_gen::Menu;
    using JniType = jobject;

    using Boxed = NativeMenu;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeMenu>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeMenu>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeMenu() : JniEnum("com/siliconbear/oakstore/Menu") {}
    friend ::djinni::JniClass<NativeMenu>;
};

}  // namespace djinni_generated
