// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "NativeDish.hpp"  // my header
#include "Marshal.hpp"
#include "NativePackage.hpp"
#include "NativeServiceBinder.hpp"

namespace djinni_generated {

NativeDish::NativeDish() : ::djinni::JniInterface<::oaktree_gen::Dish, NativeDish>("com/siliconbear/oakstore/Dish$CppProxy") {}

NativeDish::~NativeDish() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_oakstore_Dish_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::oaktree_gen::Dish>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_siliconbear_oakstore_Dish_00024CppProxy_native_1serve(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_packageList, jobject j_params, jobject j_binder)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::oaktree_gen::Dish>(nativeRef);
        ref->serve(::djinni_generated::NativePackage::toCpp(jniEnv, j_packageList),
                   ::djinni::Map<::djinni::String, ::djinni::String>::toCpp(jniEnv, j_params),
                   ::djinni_generated::NativeServiceBinder::toCpp(jniEnv, j_binder));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
