// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

#pragma once

#include "djinni_support.hpp"
#include "sandwich.hpp"

namespace djinni_generated {

class NativeSandwich final : ::djinni::JniInterface<::oaktree_gen::Sandwich, NativeSandwich> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Sandwich>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Sandwich>;
    using JniType = jobject;

    using Boxed = NativeSandwich;

    ~NativeSandwich();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSandwich>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSandwich>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSandwich();
    friend ::djinni::JniClass<NativeSandwich>;
    friend ::djinni::JniInterface<::oaktree_gen::Sandwich, NativeSandwich>;

};

}  // namespace djinni_generated
