// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#include "NativeRecipe.hpp"  // my header
#include "NativeDish.hpp"
#include "NativeMenu.hpp"

namespace djinni_generated {

NativeRecipe::NativeRecipe() : ::djinni::JniInterface<::oaktree_gen::Recipe, NativeRecipe>("com/siliconbear/oakstore/Recipe$CppProxy") {}

NativeRecipe::~NativeRecipe() = default;


CJNIEXPORT void JNICALL Java_com_siliconbear_oakstore_Recipe_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::oaktree_gen::Recipe>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_oakstore_Recipe_00024CppProxy_native_1getDish(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::oaktree_gen::Recipe>(nativeRef);
        auto r = ref->get_dish();
        return ::djinni::release(::djinni_generated::NativeDish::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_siliconbear_oakstore_Recipe_00024CppProxy_native_1getMenu(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::oaktree_gen::Recipe>(nativeRef);
        auto r = ref->get_menu();
        return ::djinni::release(::djinni_generated::NativeMenu::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
