// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

#pragma once

#include "djinni_support.hpp"
#include "runnable.hpp"

namespace djinni_generated {

class NativeRunnable final : ::djinni::JniInterface<::oaktree_gen::Runnable, NativeRunnable> {
public:
    using CppType = std::shared_ptr<::oaktree_gen::Runnable>;
    using CppOptType = std::shared_ptr<::oaktree_gen::Runnable>;
    using JniType = jobject;

    using Boxed = NativeRunnable;

    ~NativeRunnable();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRunnable>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRunnable>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRunnable();
    friend ::djinni::JniClass<NativeRunnable>;
    friend ::djinni::JniInterface<::oaktree_gen::Runnable, NativeRunnable>;

};

}  // namespace djinni_generated
