// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

package com.siliconbear.oakstore;

public abstract class Handler {
    public abstract void post(Runnable runnable);
}
