// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

package com.siliconbear.oakstore;

public enum Menu {
    CONFIG_MODULE,
    CATALOG_MODULE,
    CHECKOUT_MODULE,
    ;
}
