// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from simi.djinni

package com.siliconbear.oakstore;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Sandwich {
    public abstract void getRecipe(Chef chef);

    public static native Sandwich getInstance();

    private static final class CppProxy extends Sandwich
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void getRecipe(Chef chef)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_getRecipe(this.nativeRef, chef);
        }
        private native void native_getRecipe(long _nativeRef, Chef chef);
    }
}
