// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

package com.siliconbear.oakstore;

public abstract class Service {
    public abstract Handler poolHandler();

    public abstract void onCreate();

    public abstract void onStart(String name, Runnable runnable);
}
