// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

package com.siliconbear.oakstore;

public abstract class ServiceBinder {
    public abstract LoadType loadType();

    public abstract void onError(String message);

    public abstract void onLoad(String message, boolean cache, SimpleCursor cursor);
}
