// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from application.djinni

package com.siliconbear.oakstore;

public abstract class System {
    public abstract String getPath();

    public abstract SimpleCursor query(String database, String query);
}
